server:
  port: 30004
 

# MySQL Data Source Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/legizlawyer
    username: root
    password: admin
    # MySQL Dialect configuration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      dll-auto: update

  # Logging Level Configuration

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
  #Swagger
springdoc:
  api-docs:
    path: /legiz-lawyer-api-docs
  swagger-ui:
    path: /legiz-lawyer-api-docs-ui.html
